global class cls_transaction_dettaglio {
    @AuraEnabled
    public String transaction_nome;	//
    @AuraEnabled
    public String transaction_cognome;	//
    @AuraEnabled
    public String transaction_mail;	//
    @AuraEnabled
    public String transaction_importo;	//79300
    @AuraEnabled
    public String transaction_importoRifiutato;	//0
    @AuraEnabled
    public String transaction_divisa;	//EUR
    @AuraEnabled
    public String transaction_stato;	//Contabilizzato
    @AuraEnabled
    public String transaction_codiceTransazione;	//936eca41-0ec8-4512-bb06-e69bf2
    @AuraEnabled
    public String transaction_parametriAggiuntivi;	//num_contratto=cn_20220120143852469_e49f3758
    @AuraEnabled
    public String transaction_controvaloreValuta;	//
    @AuraEnabled
    public Integer transaction_decimaliValuta;	//0
    @AuraEnabled
    public String transaction_tassoCambio;	//
    @AuraEnabled
    public String transaction_codiceValuta;	//
    @AuraEnabled
    public String transaction_flagValuta;	//
    @AuraEnabled
    public cls_transaction_operazioni[] transaction_operazioni;
}