global class cls_transaction_operazioni {
    @AuraEnabled
    public String transaction_tipoOperazione;	//CONTAB.
    @AuraEnabled
    public String transaction_importo;	//79300
    @AuraEnabled
    public String transaction_divisa;	//EUR
    @AuraEnabled
    public String transaction_stato;	//Contabilizzato
    @AuraEnabled
    public String transaction_dataOperazione;	//2022-01-21 01:00:34.0
    @AuraEnabled
    public String transaction_utente;	//
    @AuraEnabled
    public String transaction_idContabParzialePayPal;	//xxxxxxx
}