global class DmxAddress {
    @AuraEnabled
    public String address_id;
    @AuraEnabled
    public String address_iddatamax;
    @AuraEnabled
    public String address_type;
    @AuraEnabled
    public String address_streetname;
    @AuraEnabled
    public String address_streetnumber;
    @AuraEnabled
    public String address_city;
    @AuraEnabled
    public String address_province;
    @AuraEnabled
    public String address_zipcode;
    @AuraEnabled
    public String address_note;
    @AuraEnabled
    public String address_country;
    @AuraEnabled
    public String address_hamlet;
}