global class DmxContact {
    @AuraEnabled
    public String contact_id;
    @AuraEnabled
    public String contact_iddatamax;
    @AuraEnabled
    public String contact_firstname;
    @AuraEnabled
    public String contact_lastname;
    @AuraEnabled
    public String contact_fiscalcode;
    @AuraEnabled
    public Date contact_birthdate;
    @AuraEnabled
    public String contact_email;
    @AuraEnabled
    public String contact_gender;
    @AuraEnabled
    public String contact_phone;
    @AuraEnabled
    public String contact_phoneprefix;
    @AuraEnabled
    public String contact_mobile;
    @AuraEnabled
    public String contact_mobileprefix;
    @AuraEnabled
    public String contact_type;
    @AuraEnabled
    public String contact_otherphone;
    @AuraEnabled
    public String contact_fax;
    @AuraEnabled
    public String contact_homephone;
    @AuraEnabled
    public String contact_nascitaluogo;
    @AuraEnabled
    public String contact_nascitaprovincia;
    @AuraEnabled
    public String contact_doctipo;
    @AuraEnabled
    public String contact_docnumero;
    @AuraEnabled
    public String contact_docrilasciatoda;
    @AuraEnabled
    public Date contact_docdatarilascio;
    @AuraEnabled
    public Date contact_docdatascadenza;
    @AuraEnabled
    public String acr_roles;
}