/*
 *   @TestClass: IdentityServerApiControllerTest
 *   @MockClass: IdentityServerApiControllerMock
*/
global class IdentityServerParams {
    
    @AuraEnabled
    public String nome;
    @AuraEnabled
    public String cognome;
    @AuraEnabled
    public String email;
    @AuraEnabled
    public String username;
    @AuraEnabled
    public Datetime scadenza;
    @AuraEnabled
    public Boolean isReportEnabled;
    @AuraEnabled
    public String idSub;
    @AuraEnabled
    public String emailLanguage;
    @AuraEnabled
    public String account_id;

}