global class NexiPaymentResponse {
	@AuraEnabled
    public String transaction_esito;	//OK
    @AuraEnabled
	public String transaction_idOperazione;	//21763529
    @AuraEnabled
	public String transaction_timeStamp;	//1642755144070
    @AuraEnabled
	public String transaction_scadenza;	//2022-01-20
    @AuraEnabled
	public String transaction_mac;	//c767dde6f90dd5ff45964507379d8352c3ebcb14
	@AuraEnabled
	public cls_transaction_report[] transaction_report;
}