global class VIR_Tessere {

    @AuraEnabled
    public String asset_cardnumber;
    @AuraEnabled
    public Double asset_residualcredit;
    @AuraEnabled
    public String asset_status;
    @AuraEnabled
    public Date asset_activationdate;
    @AuraEnabled
    public Date asset_duedate;
    @AuraEnabled
    public String asset_vettura;
    @AuraEnabled
    public String asset_targa;
    @AuraEnabled
    public String asset_origine;
    @AuraEnabled
    public Boolean asset_remoteenabled;
    @AuraEnabled
    public String asset_uidrfid;
    @AuraEnabled
    public String asset_idrfid;
    @AuraEnabled
    public Date asset_deactivationdate;
    @AuraEnabled
    public Datetime asset_createddate;
    @AuraEnabled
    public Datetime asset_modifieddate;
    @AuraEnabled
    public String asset_firstname;
    @AuraEnabled
    public String asset_lastname;
    @AuraEnabled
    public String asset_email;
    @AuraEnabled
    public String asset_contractstatus;
    @AuraEnabled
    public String asset_contactidmobility;
    
}